#! /usr/bin/env ruby
$: << File.expand_path(File.join(File.dirname(__FILE__), 'lib'))
require 'json'
require 'socket'
require 'timeout'
require 'panoptimon-collector-smtp'

client = Panoptimon::Collector::SMTP.new(JSON.parse(ARGV[0]))
puts JSON.generate(client.banner)
