#! /usr/bin/env ruby

$: << File.expand_path(File.join(File.dirname(__FILE__), 'lib'))
require 'json'
require 'panoptimon-collector-ssh'

client = Panoptimon::Collector::SSH.new(JSON.parse(ARGV[0]))
puts client.info


