#! /usr/bin/env ruby

$: << File.expand_path(File.join(File.dirname(__FILE__), 'lib'))
require 'rubygems'
require 'json'
require 'panoptimon-collector-nginx'

client = Panoptimon::Collector::Nginx.new(JSON.parse(ARGV[0]))
puts client.info.to_json

