#!/bin/sh

echo 'fmd:///module/ses-log-transport                                       degraded
fmd:///module/eft                                                     degraded
'
# fmd:///module/just-pretending                                         not working'
